---

- name: Create directory for proxy if it does not exist
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  when: docker_proxy

- name: create http-proxy.conf
  copy:
    content: |
      [Service]
      Environment="HTTP_PROXY={{ docker_http_proxy }}" "NO_PROXY={{ docker_no_proxy }}"
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart docker
  when: docker_http_proxy | length > 0

- name: create http-proxy.conf
  copy:
    content: |
      [Service]
      Environment="HTTPS_PROXY={{ docker_https_proxy }}" "NO_PROXY={{ docker_no_proxy }}"
    dest: /etc/systemd/system/docker.service.d/https-proxy.conf
  notify: restart docker
  when: docker_https_proxy | length > 0
